### PR TITLE
Add Wayland

### PR DESCRIPTION
**Pull request by Randl**

### CODE REVIEW

**Comment by SvyatoslavRazmyslov** [comment]
This project is too small (~40 files) and there may be not enough material for an article. It would be more convenient for you to check it yourself, using a [free version](http://www.viva64.com/en/b/0457/) of the analyzer.

**Comment by Randl** [comment]
@SvyatoslavRazmyslov Just to make it clear: SQLite is basically one file and still was added. Are there additional considerations?

**Comment by SvyatoslavRazmyslov** [comment]
@Randl,

I download the source code and count files by the extension. Some of the files may not take part in the build or be a part of some other libraries, that's why I pay attention is that the total number is big enough. In SQLite  the number of files > 200. If during the analysis it turns out that the files are not related to the project, I will delete it.

**Comment by Randl** [comment]
@SvyatoslavRazmyslov Number of files is hardly a good indicator of size of the project, it's hard for me to believe that SQLite is bigger project than Wayland.
Also SQLite is usually distributed as one big [C file](https://www.sqlite.org/amalgamation.html), that was the reason I said its single file. Of course, concatenation doesn't affects size of the project, that's why number of files is questionable criterion. 

I've used script from [here](http://stackoverflow.com/a/32154303/1894478) to estimate number of LoC of Wayland, and its ~35000, which sound not that small.

Moreover, Wayland is pretty important project for Linux, so I'd like to ask you to check it anyways even if you think it's not big enough.

**Comment by SvyatoslavRazmyslov** [comment]
@Randl We will write a comparison article about Wayland, X.Org and Mir. I cannot know everything about all the projects, that's why such discussions are very useful. Thank you for the information.

**Pull request merged**
