### PR TITLE
Add SVG Cleaner

### PR DESCRIPTION
**Pull request by SauronfromMordor**

### CODE REVIEW

**Comment by SvyatoslavRazmyslov** [comment]
SVG Cleaner is written in RUST and GUI project is too small and there may be not enough material for an article. It would be more convenient for you to check it yourself, using a [free version](http://www.viva64.com/en/b/0457/) of the analyzer.

**Comment by SauronfromMordor** [comment]
>there may be not enough material for an article.

OK, you're free to do as you want, but don't you want to make combined articles for several projects? It would be great for ones that have a common sphere of application.
Yes, I understand, you don't have to spend your time, but many people may find these little projects by your articles.

**Comment by SvyatoslavRazmyslov** [comment]
We are planning to write a combined article about Wayland, X.Org and Mir. You should understand that we don't use absolutely all the suggested programs, that's why we don't know which programs are the best to combine.

**Comment by SauronfromMordor** [comment]
OK, I understood.
By the way, could you re-check Tesseract (https://www.viva64.com/en/b/0257/)? It's almost 3 years from the first check, it would be great to try updated PVS.

**Pull request closed without merging**
